- id: vcluster-on-pirate
  name: vCluster on Pirate
  description: Disposable vCluster hosted by the Pirate OpenShift cluster.
  availability: default
  workflow: configuration/workflow-vcluster-on-pirate.yaml
  parameters:
    - name: name
      description: Name of the vCluster to create.
      value: vcluster
      kind: required

    - name: namespace
      description: Namespace in which to host the vCluster.
      value: infra-vclusters
      kind: hardcoded

  artifacts:
    - name: kubeconfig
      description: Kubeconfig for connecting to the vCluster.
      tags: [connect]

    - name: cluster-name
      description: Name of the created vCluster.
