apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-vcluster-pirate-runner
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infra-vcluster-pirate-runner
rules:
  - apiGroups: [""]
    resources: [pods, nodes, nodes/status, nodes/metrics, nodes/stats, nodes/proxy]
    verbs: [get, list, watch]
  - apiGroups: ["storage.k8s.io"]
    resources: [storageclasses, csinodes, csidrivers, csistoragecapacities]
    verbs: [get, list, watch]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: [gatewayclasses]
    verbs: [get, list, watch]
  - apiGroups: ["config.openshift.io"]
    resources: [ingresses]
    verbs: [get, list, watch]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterrolebindings
      - clusterroles
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: [customresourcedefinitions]
    verbs: [get, list, watch, create, update, patch, delete]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infra-vcluster-pirate-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: infra-vcluster-pirate-runner
subjects:
  - kind: ServiceAccount
    name: infra-vcluster-pirate-runner
    namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: infra-vcluster-pirate-runner
  namespace: infra-vclusters-pirate
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - events
      - persistentvolumeclaims
      - pods
      - resourcequotas
      - secrets
      - serviceaccounts
      - services
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: ["apps"]
    resources: [daemonsets, deployments, replicasets, statefulsets]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: ["batch"]
    resources: [jobs]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: ["coordination.k8s.io"]
    resources: [leases]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: ["policy"]
    resources: [poddisruptionbudgets]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: ["route.openshift.io"]
    resources: [routes]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: [rolebindings, roles]
    verbs: [get, list, watch, create, update, patch, delete]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infra-vcluster-pirate-runner
  namespace: infra-vclusters-pirate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infra-vcluster-pirate-runner
subjects:
  - kind: ServiceAccount
    name: infra-vcluster-pirate-runner
    namespace: default
