apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-vcluster-pirate-runner
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infra-vcluster-pirate-runner
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - events
      - persistentvolumeclaims
      - pods
      - serviceaccounts
      - services
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: ["apps"]
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: ["batch"]
    resources: [jobs]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: ["coordination.k8s.io"]
    resources: [leases]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: ["policy"]
    resources: [poddisruptionbudgets]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: ["route.openshift.io"]
    resources: [routes]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: ["config.openshift.io"]
    resources: [ingresses]
    verbs: [get, list, watch]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterrolebindings
      - clusterroles
      - rolebindings
      - roles
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: [customresourcedefinitions]
    verbs: [get, list, watch, create, update, patch, delete]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infra-vcluster-pirate-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: infra-vcluster-pirate-runner
subjects:
  - kind: ServiceAccount
    name: infra-vcluster-pirate-runner
    namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: infra-vcluster-pirate-secrets
  namespace: infra-vclusters-pirate
rules:
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get, list, watch, create, update, patch, delete]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infra-vcluster-pirate-secrets
  namespace: infra-vclusters-pirate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infra-vcluster-pirate-secrets
subjects:
  - kind: ServiceAccount
    name: infra-vcluster-pirate-runner
    namespace: default
