apiVersion: v1
kind: Secret
metadata:
  name: infra-vcluster-pirate-runner-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: infra-vcluster-pirate-runner
type: kubernetes.io/service-account-token
