apiVersion: apps/v1
kind: Deployment

metadata:
  name: infra-server-deployment
  namespace: infra
  labels:
    app.kubernetes.io/name: infra-server
    app.kubernetes.io/version: {{ .Values.tag }}
    app: infra-server

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: infra-server

  template:
    metadata:
      namespace: infra
      labels:
        app.kubernetes.io/name: infra-server
        app: infra-server

    spec:
      containers:
        - name: infra-server
          image: {{ default "quay.io/rhacs-eng/infra-server" .Values.image_repository }}:{{ required "A valid .Values.tag entry is required!" .Values.tag }}
          env:
            - name: TEST_MODE
              value: "{{ .Values.testMode }}"
            - name: MINIO_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: infra-server-secrets
                  key: minio-endpoint
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: infra-server-secrets
                  key: minio-access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: infra-server-secrets
                  key: minio-secret-key
            - name: MINIO_SECURE
              valueFrom:
                secretKeyRef:
                  name: infra-server-secrets
                  key: minio-secure
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          command:
            - /infra-server
            - -config-dir
            - /configuration
          ports:
            - name: https
              containerPort: 8443
            - name: metrics
              containerPort: 9101
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /configuration
              name: configuration
              readOnly: true

      volumes:
        - name: configuration
          {{- if .Values.oidc_secret_name }}
          projected:
            sources:
              - secret:
                  name: infra-server-secrets
              - secret:
                  name: {{ .Values.oidc_secret_name }}
          {{- else }}
          secret:
            secretName: infra-server-secrets
          {{- end }}
      imagePullSecrets:
        - name: infra-image-registry-pull-secret
