{{- if not .Values.existing_config_secret_name }}
apiVersion: v1
kind: Secret

metadata:
  name: infra-server-secrets
  namespace: infra
  labels:
    app.kubernetes.io/name: infra-server

data:
  {{- if not .Values.oidc_secret_name }}
  oidc.yaml: |-
    {{- tpl (required ".Values.oidc_yaml is undefined when oidc_secret_name is unset" .Values.oidc_yaml | b64dec) . | b64enc | nindent 4 }}
  {{- end }}

  cert.pem: |-
    {{ required ".Values.tls__cert_pem is undefined" .Values.tls__cert_pem | nindent 4 }}

  key.pem: |-
    {{ required ".Values.tls__key_pem is undefined" .Values.tls__key_pem | nindent 4 }}

  infra.yaml: |-
    {{ required ".Values.infra_yaml is undefined" .Values.infra_yaml }}

  minio-endpoint: {{ required ".Values.minio_endpoint is undefined" .Values.minio_endpoint | b64enc | quote }}
  minio-access-key: {{ required ".Values.minio_access_key is undefined" .Values.minio_access_key | b64enc | quote }}
  minio-secret-key: {{ required ".Values.minio_secret_key is undefined" .Values.minio_secret_key | b64enc | quote }}
  minio-secure: {{ default "false" .Values.minio_secure | b64enc | quote }}

  flavors.yaml: |-
    {{- tpl (.Files.Get "static/flavors.yaml") . | b64enc | nindent 4 }}

  workflow-vcluster-on-pirate.yaml: |-
    {{- tpl (.Files.Get "static/workflow-vcluster-on-pirate.yaml") . | b64enc | nindent 4 }}

{{- end }}

{{- if .Values.pullSecrets.quay }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson

metadata:
  name: infra-image-registry-pull-secret
  namespace: infra

data:
  .dockerconfigjson: {{ template "pull-secret" .Values.pullSecrets.quay }}
{{- end }}
