---
apiVersion: v1
kind: Secret
metadata:
  name: minio-artifact-credentials
  namespace: argo
type: Opaque
stringData:
  accesskey: {{ required ".Values.minio_access_key is undefined" .Values.minio_access_key | quote }}
  secretkey: {{ required ".Values.minio_secret_key is undefined" .Values.minio_secret_key | quote }}
